version: 2
languages:
  lua:
    - format-command: stylua --search-parent-directories -
      format-stdin: true
  yaml:
    - format-command: ~/.local/bin/prettier --stdin-filepath ${INPUT}
      format-stdin: true
  javascript:
    - format-command: ~/.local/bin/prettier --stdin-filepath ${INPUT}
      format-stdin: true
    - lint-command: eslint -f visualstudio --stdin --stdin-filename ${INPUT}
      lint-ignore-exit-code: true
      lint-stdin: true
      lint-formats:
        - '%f(%l,%c): %tarning %m'
        - '%f(%l,%c): %rror %m'
  zsh:
    - format-command: shfmt -i 2 -ci -s -bn
      format-stdin: true
  tex:
    - format-command: latexindent
      format-stdin: true
  bib:
    - format-command: bibtex-tidy --curly --sort --sort-fields --trailing-commas --wrap --drop-all-caps -
      format-stdin: true
